=== strikebuster/keisuke/doc/framework.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://keisuke/framework" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:keisuke="http://keisuke/framework">

    <simpleType name="PathPattern">
    	<restriction base="string"></restriction>
    </simpleType>

    <complexType name="SpecificType">
    	<sequence>
    		<element name="PathPattern" type="keisuke:PathPattern"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="group" type="string"></attribute>
    </complexType>

    <complexType name="Framework">
    	<sequence>
    		<element name="SpecificType" type="keisuke:SpecificType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="group" type="string"></attribute>
    </complexType>

    <element name="FrameworkDefinitions"
    	type="keisuke:FrameworkDefinitions">
    </element>
    
    <complexType name="FrameworkDefinitions">
    	<sequence>
    		<element name="Framework" type="keisuke:Framework" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== strikebuster/keisuke/core/keisuke/test/data/ktestf2.xml
<?xml version="1.0" encoding="UTF-8"?>
<keisuke:FrameworkDefinitions xmlns:keisuke="http://keisuke/framework" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://keisuke/framework framework.xsd ">
  <keisuke:Framework name="OW" group="ObjectWorks">
    <keisuke:SpecificType name="HTML" group="Web">
      <keisuke:PathPattern>.*/webapp/.*\.html?$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="CSS" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.css$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JavaScript" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.js$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JSP" group="SpringMVC">
    	<keisuke:PathPattern>.*/webapp/.*\.jsp$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="XHTML" group="JSF">
    	<keisuke:PathPattern>.*/webapp/.*\.xhtml$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="生成XML" group="JSF">
    	<keisuke:PathPattern>.*/webapp/.*/.*pages\.xml$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="生成Java" group="OW">
    	<keisuke:PathPattern>.*/java/.*/.*(ActionBase|Logic|Service|Dto)\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Java" group="OW">
    	<keisuke:PathPattern>.*/java/.*/.*\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="DAO層Java" group="JPA/MyBatis">
    	<keisuke:PathPattern>.*/java/.*/(.*Dao|entity/.*)\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="MyBatis" group="MyBatis">
    	<keisuke:PathPattern>.*/resources/.*/.*SqlClient\.xml$</keisuke:PathPattern>
    </keisuke:SpecificType>
  </keisuke:Framework>

  <keisuke:Framework name="O3W" group="ObjectWorks">
    <keisuke:SpecificType name="HTML" group="Web">
      <keisuke:PathPattern>.*/webapp/.*\.html?$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="CSS" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.css$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JavaScript" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.js$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JSP" group="O3W">
    	<keisuke:PathPattern>.*/webapp/.*\.jsp$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="生成XML" group="O3W">
    	<keisuke:PathPattern>.*/WEB-INF/.*_Def/.*\.xml$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Java" group="O3W">
    	<keisuke:PathPattern>.*/java/.*/.*\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
  </keisuke:Framework>
</keisuke:FrameworkDefinitions>

=== strikebuster/keisuke/core/keisuke/test/data/ktestf.xml
<?xml version="1.0" encoding="UTF-8"?>
<keisuke:FrameworkDefinitions xmlns:keisuke="http://keisuke/framework" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://keisuke/framework framework.xsd ">
  <keisuke:Framework name="OW" group="ObjectWorks">
    <keisuke:SpecificType name="HTML" group="Web">
      <keisuke:PathPattern>.*/webapp/.*\.html?$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="CSS" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.css$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JavaScript" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.js$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JSP" group="SpringMVC">
    	<keisuke:PathPattern>.*/webapp/.*\.jsp$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="XHTML" group="JSF">
    	<keisuke:PathPattern>.*/webapp/.*\.xhtml$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="XML_Gen" group="JSF">
    	<keisuke:PathPattern>.*/webapp/.*/.*pages\.xml$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Java_Gen" group="OW">
    	<keisuke:PathPattern>.*/java/.*/.*(ActionBase|Logic|Service|Dto)\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Java" group="OW">
    	<keisuke:PathPattern>.*/java/.*/.*\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="MyBatis" group="MyBatis">
    	<keisuke:PathPattern>.*/resources/.*/.*SqlClient\.xml$</keisuke:PathPattern>
    </keisuke:SpecificType>
  </keisuke:Framework>
</keisuke:FrameworkDefinitions>

=== strikebuster/keisuke/doc/framework.xml
<?xml version="1.0" encoding="UTF-8"?>
<keisuke:FrameworkDefinitions xmlns:keisuke="http://keisuke/framework" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://keisuke/framework framework.xsd ">
  <keisuke:Framework name="Struts" group="Struts">
    <keisuke:SpecificType name="HTML" group="Web">
      <keisuke:PathPattern>.*/webapp/.*\.html?$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="CSS" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.css$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JavaScript" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.js$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JSP" group="Struts">
    	<keisuke:PathPattern>.*/webapp/.*\.jsp$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ConfigXML" group="Struts">
    	<keisuke:PathPattern>.*/WEB-INF/.*/struts-config\.xml$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ValidationXML" group="Struts">
    	<keisuke:PathPattern>.*/WEB-INF/.*/.*valid.*\.xml$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ActFormBeanJava" group="Struts">
    	<keisuke:PathPattern>.*/webapp/.*/.*Bean\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ActionJava" group="Struts">
    	<keisuke:PathPattern>.*/webapp/.*/.*Action\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Java" group="Struts">
    	<keisuke:PathPattern>.*/java/.*/.*\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
  </keisuke:Framework>

  <keisuke:Framework name="Velocity" group="Velocity">
    <keisuke:SpecificType name="HTML" group="Web">
      <keisuke:PathPattern>.*/webapp/.*\.html?$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="CSS" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.css$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JavaScript" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.js$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Template" group="Velocity">
    	<keisuke:PathPattern>.*/webapp/.*/.*\.vm$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ContextJava" group="Velocity">
    	<keisuke:PathPattern>.*/webapp/.*/.*Context\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ServletJava" group="Velocity">
    	<keisuke:PathPattern>.*/webapp/.*/.*Servlet\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Java" group="Velocity">
    	<keisuke:PathPattern>.*/java/.*/.*\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
  </keisuke:Framework>

  <keisuke:Framework name="Spring" group="Spring">
    <keisuke:SpecificType name="HTML" group="Web">
      <keisuke:PathPattern>.*/webapp/.*\.html?$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="CSS" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.css$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JavaScript" group="Web">
    	<keisuke:PathPattern>.*/webapp/.*\.js$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JSP" group="SpringMVC">
    	<keisuke:PathPattern>.*/webapp/.*\.jsp$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ControllerJava" group="SpringMVC">
    	<keisuke:PathPattern>.*/webapp/.*/.*\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ContextXML" group="Spring">
    	<keisuke:PathPattern>.*/WEB-INF/.*Context\.xml$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="BeanXML" group="Spring">
    	<keisuke:PathPattern>.*/.*bean.*/.*\.xml$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Java" group="Spring">
    	<keisuke:PathPattern>.*/java/.*/.*\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="DAOJava" group="JDBC/Hibernate">
    	<keisuke:PathPattern>.*/ejb/.*/(.*Dao|entity/.*)\.java$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Hibernate" group="Hibernate">
    	<keisuke:PathPattern>.*/ejb/.*/.*hbm\.xml$</keisuke:PathPattern>
    </keisuke:SpecificType>
  </keisuke:Framework>

  <keisuke:Framework name="ASP.NET_MVC" group="ASP.NET">
    <keisuke:SpecificType name="HTML" group="Web">
      <keisuke:PathPattern>.*/public/.*\.html?$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="CSS" group="Web">
    	<keisuke:PathPattern>.*/public/.*\.css$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JavaScript" group="Web">
    	<keisuke:PathPattern>.*/public/.*\.js$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ControllerC#" group="ASP.NET">
    	<keisuke:PathPattern>.*/contorollers/.*\.cs$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ControllerVB" group="ASP.NET">
    	<keisuke:PathPattern>.*/contorollers/.*\.vb$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ModelC#" group="ASP.NET">
    	<keisuke:PathPattern>.*/models/.*\.cs$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ModelVB" group="ASP.NET">
    	<keisuke:PathPattern>.*/models/.*\.vb$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="View" group="ASP.NET">
    	<keisuke:PathPattern>.*/views/.*\.as.x$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ViewC#" group="ASP.NET">
    	<keisuke:PathPattern>.*/views/.*\.cs$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="ViewVB" group="ASP.NET">
    	<keisuke:PathPattern>.*/views/.*\.vb$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="C#" group="ASP.NET">
    	<keisuke:PathPattern>.*/.*\.cs$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="VB" group="ASP.NET">
    	<keisuke:PathPattern>.*/.*\.vb$</keisuke:PathPattern>
    </keisuke:SpecificType>
  </keisuke:Framework>

  <keisuke:Framework name="Rails" group="RubyOnRails">
    <keisuke:SpecificType name="HTML" group="Web">
      <keisuke:PathPattern>.*/public/.*\.html?$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="CSS" group="Web">
    	<keisuke:PathPattern>.*/public/.*\.css$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="JavaScript" group="Web">
    	<keisuke:PathPattern>.*/public/.*\.js$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Controller" group="Rails">
    	<keisuke:PathPattern>.*/contorollers/.*\.rb$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Model" group="Rails">
    	<keisuke:PathPattern>.*/models/.*\.rb$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="View" group="Rails">
    	<keisuke:PathPattern>.*/views/.*\.erb$</keisuke:PathPattern>
    </keisuke:SpecificType>
    <keisuke:SpecificType name="Ruby" group="Ruby">
    	<keisuke:PathPattern>.*/app/.*\.rb$</keisuke:PathPattern>
    </keisuke:SpecificType>
  </keisuke:Framework>
</keisuke:FrameworkDefinitions>
