=== strikebuster/keisuke/doc/language.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://keisuke/language" elementFormDefault="qualified" xmlns:keisuke="http://keisuke/language">










    <complexType name="BlockComment">
    	<sequence>
    		<element name="start" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="end" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="nest" type="boolean" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="LineComment">
    	<sequence>
    		<element name="start" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="needHead" type="boolean" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="needBlanc" type="boolean" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="lineDelimiter" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="escape" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <simpleType name="SkipPattern">
    	<restriction base="string"></restriction>
    </simpleType>

    <simpleType name="FileExtension">
    	<restriction base="string"></restriction>
    </simpleType>

    <complexType name="LiteralString">
    	<sequence>
    		<element name="start" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="end" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="escape" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="ScriptBlock">
    	<sequence>
    		<element name="start" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="end" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="LabelHereDoc">
    	<sequence>
    		<element name="start" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="end" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="CommentExpression">
    	<sequence>
    		<element name="start" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="CountRules">
    	<sequence>
    		<element name="SkipPattern" type="keisuke:SkipPattern"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="LineComment" type="keisuke:LineComment"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="BlockComment" type="keisuke:BlockComment"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="CommentExpression"
    			type="keisuke:CommentExpression" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="LiteralString" type="keisuke:LiteralString"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="LabelHereDoc" type="keisuke:LabelHereDoc"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="ScriptBlock" type="keisuke:ScriptBlock"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="unsupported" type="boolean" default="false"></attribute>
    	<attribute name="specialized" type="boolean" default="false"></attribute>
    	<attribute name="functional" type="boolean" default="false"></attribute>
    	<attribute name="labelHereDoc" type="boolean" default="false"></attribute>
    	<attribute name="caseInsense" type="boolean" default="false"></attribute>
    	<attribute name="indentSense" type="boolean" default="false"></attribute>
    	<attribute name="scriptlet" type="boolean" default="false"></attribute>
    	<attribute name="sameAs" type="string"></attribute>
    </complexType>


    <complexType name="Language">
    	<sequence>
    		<element name="FileExtension" type="keisuke:FileExtension"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    		<element name="CountRules" type="keisuke:CountRules"
    			maxOccurs="1" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="group" type="string"></attribute>
    </complexType>
    
    <complexType name="LanguageDefinitions">
    	<sequence>
    		<element name="Language" type="keisuke:Language" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>


    <element name="LanguageDefinitions" type="keisuke:LanguageDefinitions"></element>
</schema>

=== strikebuster/keisuke/core/keisuke/test/data/ktestl.xml
<?xml version="1.0" encoding="UTF-8"?>
<keisuke:LanguageDefinitions xmlns:keisuke="http://keisuke/language" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://keisuke/language language.xsd ">
	<keisuke:Language name="Java*" group="Java#">
		<keisuke:FileExtension>.java</keisuke:FileExtension>
	</keisuke:Language>
	<keisuke:Language name="properties*" group="Java#">
		<keisuke:FileExtension>.properties</keisuke:FileExtension>
	</keisuke:Language>
	<keisuke:Language name="JavaScript*" group="JavaScript#">
		<keisuke:FileExtension>.js</keisuke:FileExtension>
	</keisuke:Language>
	<keisuke:Language name="HTML*" group="HTML#">
		<keisuke:FileExtension>.html</keisuke:FileExtension>
		<keisuke:FileExtension>.htm</keisuke:FileExtension>
	</keisuke:Language>
	<keisuke:Language name="CSS*" group="HTML#">
		<keisuke:FileExtension>.css</keisuke:FileExtension>
	</keisuke:Language>
	<keisuke:Language name="XHTML*" group="XHTML#">
		<keisuke:FileExtension>.xhtml</keisuke:FileExtension>
	</keisuke:Language>
	<keisuke:Language name="XML*" group="XML#">
		<keisuke:FileExtension>.xml</keisuke:FileExtension>
	</keisuke:Language>
	<keisuke:Language name="XMLSchema*" group="XML#">
		<keisuke:FileExtension>.xsd</keisuke:FileExtension>
	</keisuke:Language>
	<keisuke:Language name="JSP*" group="JSP#">
		<keisuke:FileExtension>.jsp</keisuke:FileExtension>
	</keisuke:Language>
</keisuke:LanguageDefinitions>

=== strikebuster/keisuke/core/keisuke/test/data/ktestl2.xml
<?xml version="1.0" encoding="UTF-8"?>
<keisuke:LanguageDefinitions xmlns:keisuke="http://keisuke/language" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://keisuke/language language.xsd ">
	<keisuke:Language name="Java" group="Java">
		<keisuke:FileExtension>.java</keisuke:FileExtension>
		<keisuke:CountRules> 
			<keisuke:SkipPattern>^import[ \\t].+;$</keisuke:SkipPattern>
			<keisuke:SkipPattern>^package[ \\t].+;$</keisuke:SkipPattern>
			<keisuke:LineComment>
				<keisuke:start>//</keisuke:start>
			</keisuke:LineComment>
			<keisuke:BlockComment>
				<keisuke:start>/*</keisuke:start>
				<keisuke:end>*/</keisuke:end>
			</keisuke:BlockComment>
			<keisuke:LiteralString>
				<keisuke:start>&quot;</keisuke:start>
				<keisuke:end>&quot;</keisuke:end>
				<keisuke:escape>\&quot;</keisuke:escape>
			</keisuke:LiteralString></keisuke:CountRules>
	</keisuke:Language>
	<keisuke:Language name="C" group="C">
		<keisuke:FileExtension>.c</keisuke:FileExtension>
		<keisuke:FileExtension>.m</keisuke:FileExtension>
		<keisuke:FileExtension>.pc</keisuke:FileExtension>
		<keisuke:CountRules sameAs="Java">
		<keisuke:SkipPattern>^#include[ \\t].+$</keisuke:SkipPattern>
		</keisuke:CountRules>
	</keisuke:Language>
	<keisuke:Language name="VB" group="VisualBasic">
		<keisuke:FileExtension>.bas</keisuke:FileExtension>
		<keisuke:FileExtension>.cls</keisuke:FileExtension>
		<keisuke:CountRules caseInsense="false">
			<keisuke:LineComment>
				<keisuke:start>&apos;</keisuke:start>
			</keisuke:LineComment>
			<keisuke:LineComment>
				<keisuke:start>rem</keisuke:start>
				<keisuke:needBlanc>true</keisuke:needBlanc>
			</keisuke:LineComment>
			<keisuke:LiteralString>
				<keisuke:start>&quot;</keisuke:start>
				<keisuke:end>&quot;</keisuke:end>
				<keisuke:escape>&quot;&quot;</keisuke:escape>
			</keisuke:LiteralString>
		</keisuke:CountRules>
	</keisuke:Language>
	<keisuke:Language name="VBScript" group="VBScript">
		<keisuke:FileExtension>.vbs</keisuke:FileExtension>
		<keisuke:CountRules caseInsense="false">
			<keisuke:LineComment>
				<keisuke:start>&apos;</keisuke:start>
			</keisuke:LineComment>
			<keisuke:LineComment>
				<keisuke:start>rem</keisuke:start>
				<keisuke:needHead>true</keisuke:needHead>
				<keisuke:needBlanc>true</keisuke:needBlanc>
				<keisuke:lineDelimiter>:</keisuke:lineDelimiter>
			</keisuke:LineComment>
			<keisuke:LiteralString>
				<keisuke:start>&quot;</keisuke:start>
				<keisuke:end>&quot;</keisuke:end>
				<keisuke:escape>&quot;&quot;</keisuke:escape>
			</keisuke:LiteralString>
		</keisuke:CountRules>
	</keisuke:Language>
	<keisuke:Language name="PHP" group="PHP">
		<keisuke:FileExtension>.php</keisuke:FileExtension>
		<keisuke:FileExtension>.php3</keisuke:FileExtension>
		<keisuke:CountRules labelHereDoc="true" caseInsense="false" scriptlet="true">
			<keisuke:LineComment>
				<keisuke:start>#</keisuke:start>
			</keisuke:LineComment>
			<keisuke:LineComment>
				<keisuke:start>//</keisuke:start>
			</keisuke:LineComment>
			<keisuke:BlockComment>
				<keisuke:start>/*</keisuke:start>
				<keisuke:end>*/</keisuke:end>
			</keisuke:BlockComment>
			<keisuke:BlockComment>
				<keisuke:start>&lt;%--</keisuke:start>
				<keisuke:end>--%&gt;</keisuke:end>
			</keisuke:BlockComment>
			<keisuke:LiteralString>
				<keisuke:start>&apos;</keisuke:start>
				<keisuke:end>&apos;</keisuke:end>
				<keisuke:escape>\&apos;</keisuke:escape>
			</keisuke:LiteralString>
			<keisuke:LiteralString>
				<keisuke:start>&quot;</keisuke:start>
				<keisuke:end>&quot;</keisuke:end>
				<keisuke:escape>\&quot;</keisuke:escape>
			</keisuke:LiteralString>
			<keisuke:LabelHereDoc>
				<keisuke:start>&lt;&lt;&lt;@?@</keisuke:start>
				<keisuke:end>@?@</keisuke:end>
			</keisuke:LabelHereDoc>
			<keisuke:ScriptBlock>
				<keisuke:start>&lt;%</keisuke:start>
				<keisuke:end>%&gt;</keisuke:end>
			</keisuke:ScriptBlock>
			<keisuke:ScriptBlock>
				<keisuke:start>&lt;?</keisuke:start>
				<keisuke:end>?&gt;</keisuke:end>
			</keisuke:ScriptBlock>
			<keisuke:ScriptBlock>
				<keisuke:start>&lt;script language=&quot;php&quot;&gt;</keisuke:start>
				<keisuke:end>&lt;/script&gt;</keisuke:end>
			</keisuke:ScriptBlock>
		</keisuke:CountRules>
	</keisuke:Language>
	<keisuke:Language name="BAT" group="BAT">
		<keisuke:FileExtension>.bat</keisuke:FileExtension>
		<keisuke:CountRules caseInsense="false">
			<keisuke:LineComment>
				<keisuke:start>rem</keisuke:start>
				<keisuke:needHead>true</keisuke:needHead>
				<keisuke:needBlanc>true</keisuke:needBlanc>
			</keisuke:LineComment>
			<keisuke:LiteralString>
				<keisuke:start>&quot;</keisuke:start>
				<keisuke:end>&quot;</keisuke:end>
				<keisuke:escape>&quot;&quot;</keisuke:escape>
			</keisuke:LiteralString>
			<keisuke:LiteralString>
				<keisuke:start>&apos;</keisuke:start>
				<keisuke:end>&apos;</keisuke:end>
				<keisuke:escape>&apos;&apos;</keisuke:escape>
			</keisuke:LiteralString>
		</keisuke:CountRules>
	</keisuke:Language>
	<keisuke:Language name="SQL" group="SQL">
		<keisuke:FileExtension>.sql</keisuke:FileExtension>
		<keisuke:CountRules caseInsense="false">
			<keisuke:LineComment>
				<keisuke:start>--</keisuke:start>
			</keisuke:LineComment>
			<keisuke:LineComment>
				<keisuke:start>#</keisuke:start>
			</keisuke:LineComment>
			<keisuke:LineComment>
				<keisuke:start>//</keisuke:start>
			</keisuke:LineComment>
			<keisuke:LineComment>
				<keisuke:start>rem</keisuke:start>
				<keisuke:needHead>true</keisuke:needHead>
				<keisuke:needBlanc>true</keisuke:needBlanc>
			</keisuke:LineComment>
			<keisuke:BlockComment>
				<keisuke:start>/*</keisuke:start>
				<keisuke:end>*/</keisuke:end>
			</keisuke:BlockComment>
			<keisuke:LiteralString>
				<keisuke:start>&apos;</keisuke:start>
				<keisuke:end>&apos;</keisuke:end>
				<keisuke:escape>&apos;&apos;</keisuke:escape>
			</keisuke:LiteralString>
		</keisuke:CountRules>
	</keisuke:Language>
	<keisuke:Language name="Fortran" group="Fortran">
		<keisuke:FileExtension>.f</keisuke:FileExtension>
		<keisuke:FileExtension>.for</keisuke:FileExtension>
		<keisuke:FileExtension>.ftn</keisuke:FileExtension>
		<keisuke:CountRules caseInsense="false">
			<keisuke:LineComment>
				<keisuke:start>*</keisuke:start>
				<keisuke:needHead>true</keisuke:needHead>
			</keisuke:LineComment>
			<keisuke:LineComment>
				<keisuke:start>C</keisuke:start>
				<keisuke:needHead>true</keisuke:needHead>
				<keisuke:needBlanc>true</keisuke:needBlanc>
			</keisuke:LineComment>
			<keisuke:BlockComment>
				<keisuke:start>&quot;</keisuke:start>
				<keisuke:end>&quot;</keisuke:end>
			</keisuke:BlockComment>
			<keisuke:LiteralString>
				<keisuke:start>&quot;</keisuke:start>
				<keisuke:end>&quot;</keisuke:end>
				<keisuke:escape>&quot;&quot;</keisuke:escape>
			</keisuke:LiteralString>
			<keisuke:LiteralString>
				<keisuke:start>&apos;</keisuke:start>
				<keisuke:end>&apos;</keisuke:end>
				<keisuke:escape>&apos;&apos;</keisuke:escape>
			</keisuke:LiteralString>
		</keisuke:CountRules>
	</keisuke:Language>
</keisuke:LanguageDefinitions>
